CONTRIBUTING.md
README.md
build.gradle.kts
buildSrc/build.gradle.kts
instrumentation/build.gradle.kts

Resolves #4. 
I chose the filename prefix to be `opentelemetry-android` which ends up generating `opentelemetry-android-debug.aar` and `opentelemetry-android-release.aar`. I'm not sure why there are both debug and release variants, and if we'll want to publish both? For now, at least it's an improvement on `instrumentation-debug.aar` 🙃 
I also added a `CONTRIBUTING.md` and made a few `README.md` additions.

Improve output artifact names

---

.github/workflows/build.yaml
.github/workflows/reusable-workflow-notification.yml

This should also automatically create an issue if/when the build step fails. 
This is also a likely candidate place to publish a snapshot build, so I added a TODO. Relates to #9.

Add workflow to run build when main is merged.

---

instrumentation/build.gradle.kts

Rather than having 3 different versions, let's just have one and source the instrumentation bill-of-materials (bom). Doing this allows us to keep the versions in sync in a more sane way.

Simplify otel versioning via bom

---

.github/CODEOWNERS

We talked about this in the last SIG and @jack-berg and @trask agreed to be `CODEOWNERS` for a period to help get the project going and reduce time-to-merge across timezones.

Adding @jack-berg and @trask as codeowners

---

.github/workflows/codeql-daily.yml

Getting ahead of the security audit by adding nightly codeql like the other otel repos. Copied verbatim from the `opentelemetry-java` repo.

Add codeql to run nightly

---

.github/workflows/codeql-daily.yml

I tested the codeql workflow and it failed because of copypasta using the wrong workflow name. 🤦🏻

Fix workflow filename used by codeql

---

renovate.json5

Over in #23 there is a lookup warning for a nonsensical maven package, which is really just a property sourced from gradle.properties and put into an android resource value. Let's try excluding it.

Exclude mangled package from gradle.properties

---

instrumentation/build.gradle.kts

This was unfortunately causing an unparseable pom to be published: https://oss.sonatype.org/content/repositories/snapshots/io/opentelemetry/android/instrumentation/0.1.0-alpha-SNAPSHOT/instrumentation-0.1.0-alpha-20230829.211843-1.pom
Note that the version is missing from the bom in the `<dependencyManagement>` section.  We only need the topmost bom, which is instrumentation.

Remove otel core bom

---

instrumentation/src/main/java/io/opentelemetry/android/AndroidResource.java
instrumentation/src/test/java/io/opentelemetry/android/AndroidResourceTest.java

As per our discussion in previous 2 client sig meetings, adding os.description attribute which would contain build number and API level as well. Below screenshot shows what os.description string looks like from debug log.
Will soon create the other PR - proposing a change in semantic conventions to add os.build and os.api.level attribute. Thanks!

Added os.description resource attribute

---

README.md

Cleaning up a side effect of copypasta.

Remove mention of APIs that only exist in splunk

---

.github/scripts/markdown-link-check-config.json
.github/scripts/markdown-link-check-with-retry.sh
.github/workflows/build.yaml
.github/workflows/reusable-markdown-link-check.yml

Resolves #18.
Copied from the other java repos, but slightly customized.

Add markdown link checker

---

.github/repository-settings.md

This matches the behavior in the instrumentation repo and is a notable reduction in click-before-merge burden. Change has already been made.

Don't require up to date

---

gradle.properties

Might it be that renovate doesn't grok the `gradle.properties` approach here?

Update to latest otel version

---

instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
instrumentation/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java

Relates to #56.
This adds two new methods to the `OpenTelemetryRumBuilder`: 
* `setPropagator(TextMapPropagator)` - replaces all configured propagators with the given one
* `addPropagator(TextMapPropagator)` - adds the propagator to the collection of configured propagators to use in the sdk
This also defaults the propagators to the same ones as the upstream sdk -- `W3CTraceContextPropagator` and `W3CBaggagePropagator`.

Allow user to customize propagators

---

instrumentation/src/main/java/io/opentelemetry/android/NoopOpenTelemetryRum.java
instrumentation/src/main/java/io/opentelemetry/android/RumConstants.java

Now that https://github.com/open-telemetry/semantic-conventions/pull/215 has landed, let's follow the convention.

Rename rum.session.id to session.id

---

instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
instrumentation/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java

Resolves #40.
This introduces a new method called `addSpanExporter()` on the OpenTelemetryRumBuilder. This is a convenience method for users who are _not_ bringing their own preconfigured SDK and want to include their own preconfigured exporter for spans.

Allow SpanExporters to be added.

---

buildSrc/src/main/kotlin/otel.android-app-conventions.gradle.kts
gradle.properties

This will avoid issues when running android tests on devices with OS version 14+, [ref](https://developer.android.com/about/versions/14/behavior-changes-all#minimum-target-api-level).

Adding android targetsdk

---

auto-instrumentation/okhttp/okhttp-3.0/agent/build.gradle.kts
auto-instrumentation/okhttp/okhttp-3.0/library/build.gradle.kts
auto-instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/OkHttp3Singletons.java
auto-instrumentation/okhttp/okhttp-3.0/testing/build.gradle.kts
buildSrc/src/main/kotlin/otel.android-app-conventions.gradle.kts
buildSrc/src/main/kotlin/otel.android-library-conventions.gradle.kts
buildSrc/src/main/kotlin/otel.java-library-conventions.gradle.kts
dependencyManagement/build.gradle.kts
gradle.properties
instrumentation/build.gradle.kts
settings.gradle.kts

This adds a dependencyManagement module to help consolidate dependencies across the project into one consistent place. This is consistent with the other java-based otel projects.
There were a few cases where I could not figure out how to propagate the constraint into `androidTestImplementation`, so those reference the version via root project variable.
This resolves #86

Add dependencyManagement

---

auto-instrumentation/okhttp/okhttp-3.0/agent/build.gradle.kts
auto-instrumentation/okhttp/okhttp-3.0/library/build.gradle.kts
auto-instrumentation/okhttp/okhttp-3.0/testing/build.gradle.kts
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/settings.gradle.kts
buildSrc/src/main/kotlin/otel.android-app-conventions.gradle.kts
buildSrc/src/main/kotlin/otel.errorprone-conventions.gradle.kts
buildSrc/src/main/kotlin/otel.java-library-conventions.gradle.kts
gradle.properties
gradle/libs.versions.toml
instrumentation/build.gradle.kts
renovate.json5

Based on [this comment](https://github.com/open-telemetry/opentelemetry-android/pull/101#issuecomment-1744354656).
For posterity -- we were unable to use the `dependencyManagemetn` style `platform()` support (like in other projects) due to [this bug in AGP](https://issuetracker.google.com/issues/248059128).

Centralizing dependencies

---

renovate.json5

See the comment in the code. This is borrowed right from [contrib](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/7f1560254eac36b3d5e25af1439c14a21c3f3d4d/.github/renovate.json5#L7-L16) just updated for our 3 packages.

Tell renovate to include alpha packages in updates

---

auto-instrumentation/okhttp/okhttp-3.0/README.md
auto-instrumentation/okhttp/okhttp-3.0/agent/src/main/java/io/opentelemetry/instrumentation/agent/okhttp/v3_0/OkHttpClientAdvice.java
auto-instrumentation/okhttp/okhttp-3.0/agent/src/main/java/io/opentelemetry/instrumentation/agent/okhttp/v3_0/callback/OkHttpCallbackAdvice.java
auto-instrumentation/okhttp/okhttp-3.0/agent/src/main/java/io/opentelemetry/instrumentation/agent/okhttp/v3_0/callback/OkHttpCallbackPlugin.java
auto-instrumentation/okhttp/okhttp-3.0/agent/src/main/resources/META-INF/net.bytebuddy/build.plugins
auto-instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/OkHttp3Singletons.java
auto-instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/OkHttpCallbackAdviceHelper.java
auto-instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/TracingCallback.java
auto-instrumentation/okhttp/okhttp-3.0/testing/src/androidTest/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/InstrumentationTest.java

Adds support for instrumenting and properly propagating the Context when making calls using OkHttp callbacks (by calling [Call.enqueue](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-call/enqueue/))

Okhttp callback support

---

auto-instrumentation/okhttp/okhttp-3.0/agent/build.gradle.kts
auto-instrumentation/okhttp/okhttp-3.0/library/build.gradle.kts

The release failed in sonatype due to missing descriptions in these poms.

Add descriptions for OkHttp poms

---

instrumentation/src/main/java/io/opentelemetry/android/RumConstants.java

Now that [#348](https://github.com/open-telemetry/semantic-conventions/pull/348) has landed, let's use the new spelling for `session.previous_id`.

Update session.previous_id spelling

---

instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRum.java
instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
instrumentation/src/main/java/io/opentelemetry/android/OtelAndroidConfig.java
instrumentation/src/main/java/io/opentelemetry/android/OtelRumConfig.java
instrumentation/src/main/java/io/opentelemetry/android/ScreenAttributesSpanProcessor.java
instrumentation/src/main/java/io/opentelemetry/android/instrumentation/startup/InitializationEvents.java
instrumentation/src/main/java/io/opentelemetry/android/instrumentation/startup/SdkInitializationEvents.java
instrumentation/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java
instrumentation/src/test/java/io/opentelemetry/android/ScreenAttributesSpanProcessorTest.java

Much of the existing instrumentation is somewhat burdensome for users to wire up correctly. The intent here is to introduce a configuration object that can be passed to the `OpenTelemetryRumBuilder` in order to more easily wire up various mobile components. This is intended to be first of several phases. This phase includes:
* Preconfigured global attributes. These are user-configured attributes that are intended to be included on every span and event.
* Network attributes (for things like connection type/subtype and carrier information)
* Screen attributes (the name of the currently visible screen)
* SDK initialization events - for tracking the startup of the sdk itself. NOTE: To keep this PR small and more easily reviewable, this implementation is left as a stub. Future PRs will fill in …

Introduce configuration for instrumentation components (phase 1)

---

instrumentation/src/main/java/io/opentelemetry/android/GlobalAttributesSpanAppender.java
instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRum.java
instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
instrumentation/src/main/java/io/opentelemetry/android/OtelRumConfig.java
instrumentation/src/test/java/io/opentelemetry/android/GlobalAttributesSpanAppenderTest.java

Resolves #128. 
Provides the ability to pass a Supplier to the GlobalAttributesSpanAppender. This allows a user to more readily change the "global" set of attributes that are always applied to spans.

Global attributes supplier

---

buildSrc/src/main/kotlin/otel.java-library-conventions.gradle.kts

Closes #138 
This should allow to set the minimum Android SDK supported by a specific `auto-instrumentation` subproject like so:
```kotlin
// library build.gradle.kts file
plugins {
id("otel.java-library-conventions")
//...
}
otelAndroid.minSdk = 26
```
This will prevent animal sniffer from complaining about code references used by the auto-instrumentation project that aren't available neither in the Android SDK 21 (the current core lib min SDK supported) nor in the desugar lib.
The README of the auto-instrumentation subproject that changes this value should mention what's the minimum supported Android API level for the auto-instrumentation to work properly, this is because some auto-instrumentations might target code found on versions above 21 while still providing some functionality and …

Making android min sdk configurable per auto-instrumentation subproject

---

auto-instrumentation/okhttp/okhttp-3.0/README.md
auto-instrumentation/okhttp/okhttp-3.0/agent/build.gradle.kts
auto-instrumentation/okhttp/okhttp-3.0/library/build.gradle.kts
auto-instrumentation/okhttp/okhttp-3.0/library/consumer-rules.pro
auto-instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/CachedSupplier.java
auto-instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/LazyInterceptor.java
auto-instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/OkHttp3Singletons.java
auto-instrumentation/okhttp/okhttp-3.0/library/src/test/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/CachedSupplierTest.java
auto-instrumentation/okhttp/okhttp-3.0/testing/build.gradle.kts
auto-instrumentation/okhttp/okhttp-3.0/testing/proguard-rules.pro
auto-instrumentation/okhttp/okhttp-3.0/testing/proguard-test-rules.pro
auto-instrumentation/okhttp/okhttp-3.0/testing/src/androidTest/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/InstrumentationTest.java
buildSrc/src/main/kotlin/otel.android-app-conventions.gradle.kts
buildSrc/src/main/kotlin/otel.android-library-conventions.gradle.kts
gradle/libs.versions.toml
instrumentation/build.gradle.kts

The OkHttp auto-instrumentation tool had an issue where it would create spans for OkHttp requests created by OTel's exporters, causing an infinite amount of spans to be created since each export would mean a new OkHttp call. Said issue was addressed as part of these PRs:
- https://github.com/open-telemetry/opentelemetry-java/pull/5918
- https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9739
This PR does the following:
* Adds tests to validate that the infinite spans issue is solved. 
* Adds proguard rules to avoid issues with a reflection call needed to identify OTel's okhttp requests, more info [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9739#discussion_r1394507569). 
* Fixes an initialization racing issue where the global …

Okhttp autoinstrumentation stabilization

---

instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
instrumentation/src/main/java/io/opentelemetry/android/config/OtelRumConfig.java
instrumentation/src/main/java/io/opentelemetry/android/instrumentation/startup/InitializationEvents.java
instrumentation/src/main/java/io/opentelemetry/android/instrumentation/startup/SdkInitializationEvents.java
instrumentation/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java

The instrumentation that reports network changes has not yet been wired up. This adds it to the configuration and enables the instrumentation in the builder's `build()`.
One additional aspect is that the `CurrentNetworkProvider` now has a setter on the `OpenTelemetryRumBuilder`. This allows existing components that may rely on this functionality to share the instance.  The creation is lazy, so that if the builder user didn't create one, it is created at build time on demand.
I expect this `CurrentNetworkProvider` sharing to hopefully not be necessary in the long term, but right now there are existing disk buffering implementations (eg. Splunk's distro) that also need to determine information about the current network availability before attempting export.

Add network change monitoring

---

auto-instrumentation/okhttp/okhttp-3.0/testing/build.gradle.kts
auto-instrumentation/okhttp/okhttp-3.0/testing/proguard-rules.pro
auto-instrumentation/okhttp/okhttp-3.0/testing/proguard-test-rules.pro
buildSrc/src/main/kotlin/otel.android-app-conventions.gradle.kts
buildSrc/src/main/kotlin/otel.android-library-conventions.gradle.kts

I [wanted to include](https://github.com/open-telemetry/opentelemetry-android/pull/159) R8/ProGuard verifications to the okhttp instrumentation test, however, R8/ProGuard doesn't seem to work well when corelib desugaring is enabled, so I've deleted the R8/ProGuard verification in this PR to address [this issue](https://github.com/open-telemetry/opentelemetry-android/issues/178).

Removing okhttp testing deobfuscation

---

instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
instrumentation/src/main/java/io/opentelemetry/android/internal/features/persistence/DiskManager.java
instrumentation/src/main/java/io/opentelemetry/android/internal/features/persistence/SimpleTemporaryFileProvider.java
instrumentation/src/main/java/io/opentelemetry/android/internal/services/CacheStorageService.java
instrumentation/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java
instrumentation/src/test/java/io/opentelemetry/android/internal/features/persistence/DiskManagerTest.java
instrumentation/src/test/java/io/opentelemetry/android/internal/features/persistence/SimpleTemporaryFileProviderTest.java

Related to #132 
This part connects the tools added in the previous part to the OpenTelemetryRumBuilder class.
* Make sure the initialization happens in a secondary thread, more info: https://github.com/open-telemetry/opentelemetry-android/issues/149.
* Set up configurable, periodic calls to export cached data as background work.

Adding disk buffering, part 2

---

gradle.properties
instrumentation/build.gradle.kts
instrumentation/src/main/java/io/opentelemetry/android/AndroidResource.java
instrumentation/src/test/java/io/opentelemetry/android/AndroidResourceTest.java

Resolves #7. This uses an AGP built-in to support for generating BuildConfig and adds the version number as a constant field. It then updates the AndroidResource to use this field instead of the resource string.
This also removes the `android.defaults.buildfeatures.buildconfig` deprecated gradle property.

Use the BuildConfig for version property

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/otel.android-app-conventions.gradle.kts
buildSrc/src/main/kotlin/otel.android-library-conventions.gradle.kts
buildSrc/src/main/kotlin/otel.java-library-conventions.gradle.kts
buildSrc/src/main/kotlin/otel.spotless-conventions.gradle.kts
gradle/libs.versions.toml

Related to [this discussion](https://github.com/open-telemetry/opentelemetry-android/issues/82).

Adding Kotlin compile support

---

instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
instrumentation/src/main/java/io/opentelemetry/android/config/OtelRumConfig.java
instrumentation/src/main/java/io/opentelemetry/android/instrumentation/startup/InitializationEvents.java
instrumentation/src/main/java/io/opentelemetry/android/instrumentation/startup/SdkInitializationEvents.java
instrumentation/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java

Add configs and automatically wire up instrumentation for:
* ANR (application not responding) detector
* Crash reporting
* Slow rendering detection
All of these instrumentations will be enabled by default, and there are config methods to disable them. There is also config to specify the polling interval for slow rendering.
Furthermore, the `OpenTelemetryRumBuilder` also allows users to provide customizers for the `CrashReporterBuilder` and `AnrDetectorBuilder`. These can be used by users or 3rd party distributions in order to provide custom/specific attribute extraction.

Additional instrumentation configs

---

auto-instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/OkHttpInstrumentationConfig.java
auto-instrumentation/okhttp/okhttp-3.0/library/src/test/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/OkHttpInstrumentationConfigTest.java

We're currently overriding the default known methods from [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/b3530840644cda051e101b688dd32ea964d213ce/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/semconv/http/HttpClientAttributesExtractorBuilder.java#L37) with an empty list when initializing the OkHttp instrumenter [here](https://github.com/open-telemetry/opentelemetry-android/blob/d7d5045c8178b0a6069ae93c1cd0b11dc6641fe0/auto-instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/OkHttp3Singletons.java#L48).
These changes will make sure that, when no custom HTTP methods are provided, we go with the default methods as they are defined in the OTel Java Instrumentation API …

Adding default known http methods to the okhttp instrumentation

---

gradle/libs.versions.toml
instrumentation/build.gradle.kts

Because the zipkin exporter was removed some time ago, these are no longer needed and should be safely removed.

Remove zipkin dependencies

---

README.md

The blockquote prevented the auto-issue linking.

README.md - Link to #73

---

buildSrc/src/main/kotlin/otel.spotless-conventions.gradle.kts

The build output in GHA is generating a lot of warnings like this:
```
"Install Android SDK Platform-Tools v.35.0.1" finished.
Configuration 'spotless996156776' was resolved during configuration time.
This is a build performance and scalability issue.
See https://github.com/gradle/gradle/issues/2298
Run with --info for a stacktrace.
Configuration 'spotless865459188' was resolved during configuration time.
This is a build performance and scalability issue.
See https://github.com/gradle/gradle/issues/2298
Run with --info for a stacktrace.
Configuration 'spotless996156776' was resolved during configuration time.
This is a build performance and scalability issue.
See https://github.com/gradle/gradle/issues/2298
Run with --info for a stacktrace.
Configuration …
```

Fix spotless warnings during build

---

android-agent/build.gradle.kts
buildSrc/src/main/kotlin/otel.publish-conventions.gradle.kts

Right now the version of the released artifacts from this project don't match. The `android-agent` one has the format: `0.x.x-alpha`, while all the other modules have this other one: `0.x.x`.
These changes aim to change the version formatting of all the artifacts in this project to match the one used by `android-agent`, i.e. appending `-alpha` to it.

Adding '-alpha' to all modules' versions

---

README.md

Address issue #295 by updating the README to note the workaround required so desugaring on debug works properly to the Java semconv module's lack of direct dependency to the OTel Java API module.
If we want validate the workaround and ensure it keeps on working, I can add my instrumentation test and apply the workaround to the PR.
BTW, I'm not a big fan of the formatting, but I can't find a style guide to suggest something better. If you want me to turn the quoted paragraph to a call-out with two bullets or whatever, please let me know.

Update README re: desugaring

---

.github/workflows/gradle-wrapper-validation.yaml
gradle/libs.versions.toml

* Supersedes #303
* Supersedes #279 
The instrumentation bom is not alpha, so this updates that while updating us to the latest. It also updates the gradle version wrapper to the latest name.

Update dependency versions.

---

.github/repository-settings.md
.github/workflows/build.yaml

So we need to set up branch protection on the `release/*` branches, and it will need to require `required-status-check` like the other java-based builds.

Release branch settings

---

.github/workflows/pr-check.yaml

In keeping consistency with the other projects, we have this new `required-status-check` requirement in the branch protection rules....but until this status is actually added to the PR builds, they will hang.

Add the required-status-check to PR builds. 

---

.github/repository-settings.md

As part of the release change process, we added protection rules for `opentelemetrybot`, which also pointed out that we were missing mention of `renovate`.

Add additional protection rules

---

.github/workflows/prepare-release-branch.yml

We append -SNAPSHOT in all non -Pfinal=true builds, so this is not needed.

Fix how next version is calculated during pre-release

---

.github/workflows/release.yml

The release process should just use (via checkout) whatever is chosen in the "workflow_dispatch" selection. No additional branch name needed.

Simplify the release process branch choice.

---

.github/workflows/release.yml

So we have code in our build (https://github.com/open-telemetry/opentelemetry-android/blob/main/android-agent/build.gradle.kts#L36) that renames the release artifact to a plainly named artifact (`opentelemetry-android.aar`), but for some unknown reason in the publish cycle  (likely the incomprehensible and nightmarish complexities of the gradle build lifecycle) that step isn't happening I guess, or is happening later. 
See [this build failure from the last release](https://github.com/open-telemetry/opentelemetry-android/actions/runs/8808081467/job/24176448700#step:11:20) as an example.
Let's just copy the release artifact for release builds.

Change name of output artifact used when creating GH release

---

android-agent/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
android-agent/src/main/java/io/opentelemetry/android/SessionIdTimeoutHandler.java
android-agent/src/main/java/io/opentelemetry/android/config/OtelRumConfig.java
android-agent/src/test/java/io/opentelemetry/android/SessionIdTimeoutHandlerTest.java

chore: added session timeout minutes config in OtelConfig

---

buildSrc/src/main/kotlin/otel.android-app-conventions.gradle.kts
gradle.properties

Setting the `targetSdkVersion` is the domain of apps, not libraries. Given the project's `minSdkVersion` is 21, apps that target 21 should be able use it, so adding this is probably too restrictive as the manifest merging process will use the highest one, which would be 23, if we left this in, which would override what the app's setting stipuates.

Remove targetSdk declaration

---

demo-app/gradle.properties

Make building the demo app in debug work by enabling the Gradle setting that makes desugaring work when minSdkVersion is set to < 24

Enable desugaring in debug for demo app

---

demo-app/build.gradle.kts
demo-app/settings.gradle.kts
gradle/libs.versions.toml

To avoid these issues: https://github.com/open-telemetry/opentelemetry-android/pull/376 and https://github.com/open-telemetry/opentelemetry-android/pull/377
These changes align the `demo-app` and `android-agent` projects to share the same AGP version. This is needed because otherwise, the `demo-app` project will refuse to compile when the `android-agent` project uses a different AGP version. This happens because the `android-agent` project is compiled as part of the `demo-app` compilation, making both projects' compilation classpath available in the same gradlew execution.

Using AGP version from single catalog

---

.github/workflows/release.yml

We don't need them, and since we're so modular now it doesn't make as much since to just publish the agent/sdk thing alone.

Don't add artifacts to the GH release page

---

build.gradle.kts
demo-app/build.gradle.kts
demo-app/gradle/libs.versions.toml
gradle/libs.versions.toml

Supersedes #380 
Using the new compose compiler plugin to fix compose version compatibilities with Kotlin 2.0.0. Also, the `1.6` min kotlin `languageVersion`/`apiVersion` has been marked as deprecated, so I've bumped it to the next minimum `1.7`.

Upgrading Kotlin to 2.0.0

---

.github/workflows/draft-change-log-entries.yaml
RELEASING.md

This is to provide a GH action to run the changelog draft script as well as updating the release instructions to mention it.

Release docs update

---

.github/workflows/draft-change-log-entries.yaml

I gave it a [try](https://github.com/open-telemetry/opentelemetry-android/actions/runs/9315211335/job/25640903132) and it failed when evaluating the regex... I read that using `sh` might cause the script to not run with `bash` so, let's see.. (any feedback is appreciated, I'm not a bash expert).

Removing sh when running the script

---

android-agent/src/test/java/io/opentelemetry/android/AndroidResourceTest.java
android-agent/src/test/java/io/opentelemetry/android/export/ModifiedSpanDataTest.java
instrumentation/anr/src/test/java/io/opentelemetry/android/instrumentation/anr/StackTraceFormatterTest.java
instrumentation/crash/src/test/java/io/opentelemetry/android/instrumentation/crash/CrashReporterTest.java
instrumentation/network/src/test/java/io/opentelemetry/android/instrumentation/network/CurrentNetworkAttributesExtractorTest.java
instrumentation/network/src/test/java/io/opentelemetry/android/instrumentation/network/NetworkAttributesSpanAppenderTest.java
instrumentation/network/src/test/java/io/opentelemetry/android/instrumentation/network/NetworkChangeMonitorTest.java
instrumentation/volley/library/src/test/java/io/opentelemetry/android/instrumentation/volley/TracingHurlStackExceptionTest.java
instrumentation/volley/library/src/test/java/io/opentelemetry/android/instrumentation/volley/TracingHurlStackTest.java
instrumentation/volley/library/src/test/java/io/opentelemetry/android/instrumentation/volley/VolleyResponseAttributesExtractorTest.java

Quite a few deprecated usages updated here. Switching to the active/contemporary versions to avoid future breakage.

Update semconv usages and reduce warning counts

---

android-agent/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
android-agent/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java

As part of #397, we introduced listeners who can get notified immediately after the otel sdk is created. This is used when creating the initialization events, but users also have the ability to add. Unfortunately, we forgot to actually call the listeners!

Actually call listeners

---

CHANGELOG.md
android-agent/build.gradle.kts
android-agent/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
android-agent/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java
demo-app/proguard-rules.pro
demo-app/src/main/java/io/opentelemetry/android/demo/OtelSampleApplication.kt

This will rebase after #421 is merged. 
So far, logs export has been completely absent. In order for logs and events to make it out of the agent, we need logs to be wired up in some form. For now, just like spans, the basic default exporter just logs to the console (visible in logcat). This also adds a method that allows customization, which the demo app now uses to export to the emulator host.
I was able to use this to see events exported as logs in a locally running collector!
And just to be extra clear, this isn't really what #142 is asking for, because it doesn't bridge the android logger...it's just otel logs.

Wire up logs export

---

demo-app/README.md
demo-app/build.gradle.kts
demo-app/collector.yaml
demo-app/compose.yaml
demo-app/gradle/libs.versions.toml
demo-app/src/main/AndroidManifest.xml
demo-app/src/main/java/io/opentelemetry/android/demo/DemoViewModel.kt
demo-app/src/main/java/io/opentelemetry/android/demo/MainActivity.kt
demo-app/src/main/java/io/opentelemetry/android/demo/MainOtelButton.kt
demo-app/src/main/java/io/opentelemetry/android/demo/OtelDemoApplication.kt

Resolves #345. This will rebase after #424.
It does a few more things with the demo app:
* Rename from `OtelSampleApplication` to `OtelDemoApplication` for consistency with project name (and otel demo)
* Wire up logs exporter
* Generate an event in addition to span for logo click on main page
* Add docker compose and collector configs
* Updates the README with instructions on how to start up the service(s).

Docker compose servers

---

android-agent/build.gradle.kts
android-agent/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
android-agent/src/main/java/io/opentelemetry/android/config/OtelRumConfig.java
instrumentation/anr/build.gradle.kts
instrumentation/anr/src/main/java/io/opentelemetry/android/instrumentation/anr/AnrDetector.java
instrumentation/anr/src/main/java/io/opentelemetry/android/instrumentation/anr/AnrDetectorToggler.java
instrumentation/anr/src/main/java/io/opentelemetry/android/instrumentation/anr/AnrInstrumentation.java
instrumentation/anr/src/test/java/io/opentelemetry/android/instrumentation/anr/AnrDetectorTest.java

This part focuses on migrating the ANR instrumentation.

Instrumentation API part 5

---

.github/scripts/markdown-link-check-config.json

The demo app references this URL for the local jaeger service, but it fails the markdown link checker. This excludes it.

Tell the markdown link checker to ignore this localhost url

---

.github/renovate.json5

See #491 and #492 and #493, which is what happens without this.

group the androidx.lifecycle dep updates for the demo app

---

instrumentation/httpurlconnection/library/src/main/java/io/opentelemetry/instrumentation/library/httpurlconnection/internal/HttpUrlConnectionSingletons.java
instrumentation/httpurlconnection/testing/build.gradle.kts
instrumentation/httpurlconnection/testing/src/androidTest/kotlin/io/opentelemetry/instrumentation/library/httpurlconnection/InstrumentationTest.kt
test-common/src/main/kotlin/io/opentelemetry/android/test/common/OpenTelemetryTestUtils.kt

This PR cleans up httpurlconnection androidTests based on learnings and discussions from PR #452 and PR #500:
- Keep tests synchronous. 
- Address any open comments.

Cleanup httpurlconnection androidTests

---

demo-app/README.md
demo-app/compose.yaml

This workaround is required for containerization to work in the latest jaeger ([1.59](https://github.com/jaegertracing/jaeger/releases/tag/v1.59.0)).
Resovles #506 .

Ensure the demo app collector is listening on all interfaces

---

CONTRIBUTING.md

Main build is failing markdown link check due to changes in the community repo.

Fix community contributing link

---

.github/workflows/codeql-daily.yml
.github/workflows/pr-check.yaml

Running android tests as part of daily checks

---

demo-app/collector.yaml

This change configures the OTLP receiver in the demo application to listen on 0.0.0.0. Previously, this was part of the default config but changed since v0.104.0.
Related to #506.

Configure OTLP receiver to listen on 0.0.0.0

---

demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/AstronomyShopActivity.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/cart/Cart.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/cart/CartViewModel.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/components/QuantityChooser.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/products/ProductDetails.kt

Adding product of specified quantity to cart and emptying cart works. QuantityChooser component moved to a separate file.

Demo app cart 

---

instrumentation/okhttp/okhttp-3.0/library/consumer-rules.pro

With SDK 1.41.0 `io.opentelemetry.exporter.internal.InstrumentationUtil` is now deprecated and replaced with `io.opentelemetry.api.internal.InstrumentationUtil` directly in the API.
Update to the 1.41.0 SDK has been done in https://github.com/open-telemetry/opentelemetry-android/pull/521 and is now merged.
As a consequence, the proguard configuration is no more needed for this class.
@LikeTheSalad can you tell me if there is anything related to `InstrumentationUtil` usage that needs to be updated here ?

remove proguard config for InstrumenationUtil

---

gradle/libs.versions.toml

We need to keep the alpha dependencies from core at the same version as core.

Keep sdk incubator same as core

---

demo-app/build.gradle.kts
demo-app/src/main/java/io/opentelemetry/android/demo/clients/RecommendationService.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/AstronomyShopActivity.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/cart/Cart.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/cart/CheckoutInfo.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/components/UpPressButton.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/products/ProductCard.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/products/ProductDetails.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/products/ProductList.kt
demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/products/RecommendedSection.kt

A simple recommendation service based on the web demo was implemented: recommended products appear on the product details and cart screen. Additionally, a "go back" arrow button was added to the product details and the checkout-info screen that allows to successfully navigate up.

Demo app: Recommendations

---

demo-app/README.md

Added a descriptions of features in the demo app readme (where TBD was), acknowledging features that are currently missing.

Demo app: features in readme

---

instrumentation/activity/build.gradle.kts
instrumentation/activity/src/main/java/io/opentelemetry/android/instrumentation/activity/ActivityLifecycleInstrumentation.kt
instrumentation/activity/src/test/java/io/opentelemetry/android/instrumentation/activity/ActivityInstrumentationTest.kt

This fixes issue #560 by calling `AppStartupTimer#start` in `ActivityLifecycleInstrumentation#install`.
Since `start` is idempotent, this will still work if a way to pass in a pre-started timer to the instrumentation is added later.
Added tests based on `SlowRenderingInstrumentationTest`. To verify the changes:
`./gradlew :instrumentation:activity:testDebugUnitTest`
`./gradlew check`

start AppStart span when installing activity lifecycle instrumentation

---

demo-app/src/main/java/io/opentelemetry/android/demo/shop/ui/Navigation.kt
demo-app/src/main/java/io/opentelemetry/android/demo/shop/ui/cart/Cart.kt

Manually instrumented the demo app to emit: navigate.to.product.details, navigate.to.checkout.info and cart.emptied events.

Demo app: Manual instrumentation

---

.github/renovate.json5

We currently have a state where renovate can push version updates for some of the core repos separately from the same `-alpha` artifacts. This can (and has) introduced breakage, so I think we should look at grouping the core versions with their alpha counterparts.

Group java core dependency updates

---

.github/renovate.json5

The attempt in #582 did not work as expected, resulting in horrible renovate ideas like #585. 
So now we just explicitly list out all of the core packages, group them together, and tell renovate to not ignore unstable, which I think means to keep the alphas (and don't favor non-alphas).

Explicitly enumerate core packages

---

demo-app/README.md
demo-app/src/main/java/io/opentelemetry/android/demo/shop/ui/components/ConfirmCrashPopUp.kt
demo-app/src/main/java/io/opentelemetry/android/demo/shop/ui/products/ProductDetails.kt

May resolve #347.
Added a way to crash the demo app through unhandled exceptions and documented it. To invoke it, try adding to cart exactly 10 of the first product on the list. The way in which `multiThreadCrashing` function works is copied from the [splunk-otel-android sample app](https://github.com/signalfx/splunk-otel-android/tree/main/sample-app) function of the same name.

Demo App crash

---

core/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
core/src/main/java/io/opentelemetry/android/features/diskbuffering/DiskBufferingConfiguration.java

Because one size can't necessarily fit all, we need to expose additional settings for the disk buffering feature.
* maxFileAgeForWriteMillis
* minFileAgeForReadMillis
* maxFileAgeForReadMillis
These map over directly to the same configurations in the contrib module, and use the same sane defaults as well.

Expose additional disk buffering configuration

---

demo-app/src/main/java/io/opentelemetry/android/demo/shop/ui/AstronomyShopActivity.kt
demo-app/src/main/java/io/opentelemetry/android/demo/shop/ui/Navigation.kt
demo-app/src/main/java/io/opentelemetry/android/demo/shop/ui/cart/CheckoutConfirmation.kt
demo-app/src/main/java/io/opentelemetry/android/demo/shop/ui/cart/CheckoutInfo.kt
demo-app/src/main/java/io/opentelemetry/android/demo/shop/ui/cart/CheckoutInfoViewModel.kt

Created `CheckoutConfirmation.kt` with an order confirmation screen, basing it off the web demo. User sees this screen after clicking "Place Order" on the CheckoutInfo screen. The cart is also cleared in the process.
Additionally, I made the form for shipping and payment information pre-filled, to be able to go to that screen without filling them in every time.

Demo app: Order confirmation

---

demo-app/src/main/java/io/opentelemetry/android/demo/about/AboutActivity.kt
demo-app/src/main/java/io/opentelemetry/android/demo/shop/ui/AstronomyShopActivity.kt

Basically the title. I don't think we should be starting the main activity again, when clicking the `Exit` button on another activity. Just finishing the current activity seems to work fine. The motivation to look into this were multiple `App start` spans emitted by the app. After those changes it doesn't happen, there are `Restarted` spans for the main activity instead. The behaviour after the change is identical to the one using the phone's build-in "go back" button while on the first screen of a non-main activity.

Demo app: don't start the main activity again, just finish the current one

---

demo-app/collector.yaml

This exporter has been replaced by the debug exporter and will be removed soon. Related to https://github.com/open-telemetry/opentelemetry-collector/pull/11037

fix: update references to logging exporter

---

README.md

We were just here to help bootstrap at the very beginning but haven't been needed for a long time already now.

Remove bootstrap approvers

---

instrumentation/okhttp/okhttp-3.0/README.md

just fixing some missing/extra `)` characters

Clean up markdown formatting in okhttp README.md

---

.github/workflows/release.yml
core/build.gradle.kts
gradle/libs.versions.toml
instrumentation/activity/build.gradle.kts
instrumentation/anr/build.gradle.kts
instrumentation/common-api/build.gradle.kts
instrumentation/crash/build.gradle.kts
instrumentation/fragment/build.gradle.kts
instrumentation/httpurlconnection/library/build.gradle.kts
instrumentation/network/build.gradle.kts
instrumentation/slowrendering/build.gradle.kts
instrumentation/startup/build.gradle.kts
instrumentation/volley/library/build.gradle.kts
test-common/build.gradle.kts

See this as an example of renovate updating the core lib versions before the instrumentation versions are updated: https://github.com/open-telemetry/opentelemetry-android/pull/630#issuecomment-2420416384
This opens a window during which our instrumentation dep could be misaligned with our core dep. This change now forces the use of boms at the instrumentation level in order to determine which versions of the core libs to use.
Because we no longer explicitly declare which version of the core libs (api/sdk) we use in the `libs.versions.toml` file, we have to grep for it at release time via `./gradlew android-agent:dependencies`.

Leverage boms for transient core deps

---

core/src/main/java/io/opentelemetry/android/common/RumConstants.java

`session.previous_id` exists in `SessionIncubatingAttributes.SESSION_PREVIOUS_ID` so we don't need it here.

Remove unused constant that exists in semconv

---

CONTRIBUTING.md

Most of the other instructions are quoted as a block, which I think made the spotless bit a little too easy for new contributors to overlook.

Make the spotless usage block level

---

.github/workflows/release.yml

Maybe this is new because the file was modified in #652, but we're seeing some weird build failures the claim that `release.yml` is malformed:
https://github.com/open-telemetry/opentelemetry-android/actions/runs/11557577328
The whitespace had been in there for at least 6 months, not sure why it's a new problem. Let's remove it and see if that goes away.

release.yml - Remove empty whitespace

---

core/src/main/java/io/opentelemetry/android/SdkPreconfiguredRumBuilder.kt
core/src/main/java/io/opentelemetry/android/instrumentation/AndroidInstrumentation.kt
core/src/test/java/io/opentelemetry/android/instrumentation/TestAndroidInstrumentation.kt
instrumentation/activity/src/main/java/io/opentelemetry/android/instrumentation/activity/ActivityLifecycleInstrumentation.kt
instrumentation/activity/src/test/java/io/opentelemetry/android/instrumentation/activity/ActivityInstrumentationTest.kt
instrumentation/anr/src/main/java/io/opentelemetry/android/instrumentation/anr/AnrInstrumentation.java
instrumentation/crash/src/main/java/io/opentelemetry/android/instrumentation/crash/CrashReporterInstrumentation.java
instrumentation/crash/src/test/java/io/opentelemetry/android/instrumentation/crash/CrashReporterTest.java
instrumentation/fragment/src/main/java/io/opentelemetry/android/instrumentation/fragment/FragmentLifecycleInstrumentation.kt
instrumentation/httpurlconnection/library/src/main/java/io/opentelemetry/instrumentation/library/httpurlconnection/HttpUrlInstrumentation.java
instrumentation/network/src/main/java/io/opentelemetry/android/instrumentation/network/NetworkChangeInstrumentation.java
instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/OkHttpInstrumentation.java
instrumentation/slowrendering/src/main/java/io/opentelemetry/android/instrumentation/slowrendering/SlowRenderingInstrumentation.java
instrumentation/slowrendering/src/test/java/io/opentelemetry/android/instrumentation/slowrendering/SlowRenderingInstrumentationTest.kt
instrumentation/startup/src/main/java/io/opentelemetry/android/instrumentation/startup/StartupInstrumentation.kt
instrumentation/startup/src/test/java/io/opentelemetry/android/instrumentation/startup/StartupInstrumentationTest.kt
instrumentation/volley/README.md

As @surbhiia described in #658, there is an unnecessary tight coupling from the `AndroidInstrumentation` implementations back to the core module.  Literally every one of the instrumentations was taking the rum instance only so that it could get access to the otel instance. 
So let's simplify this and have fewer law-of-demeter violations! This changes the `install()` API to take the OpenTelemetry instance directly.

Relax install arg from OpenTelemetryRum to OpenTelemetry instance.

---

.github/scripts/generate-release-notes.sh
RELEASING.md

This patches up some small shortcomings in the release process:
1. clarify in RELEASING.md that the PR has to be merged before the release process is run
2. fix some odd formatting in the generated release notes
3. grep for `opentelemetry-instrumentation` instead of `opentelemetry-alpha` for the instrumentation version.

Small fixes after the last release

---

core/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
core/src/main/java/io/opentelemetry/android/SessionIdLogRecordAppender.kt
core/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java
core/src/test/java/io/opentelemetry/android/SessionIdLogRecordAppenderTest.kt
instrumentation/crash/src/main/java/io/opentelemetry/android/instrumentation/crash/CrashReporter.java

I happened to notice that the crash event (log for now) didn't contain the session information...which was likely fallout from the crash event changing from a span to a log record. This led me to discover that we hadn't yet built the `SessionIdLogRecordAppender`....so here it is.

Add SessionIdLogRecordAppender

---

core/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
core/src/main/java/io/opentelemetry/android/export/BufferDelegatingMetricExporter.kt
core/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java
demo-app/src/main/java/io/opentelemetry/android/demo/MainOtelButton.kt
demo-app/src/main/java/io/opentelemetry/android/demo/OtelDemoApplication.kt

Resolves #527.
A few notes about this:
* I'm still not convinced that most users want/need metrics, but we've had enough interest lately that I think it's warranted.
* The logging exporter is based on `java.util.logging` and doesn't seem to actually template the `MetricData` values correctly, so the actual output in logcat is less than helpful.
* Maybe eventually we can make it easy for users to specify which resource attributes they want on metrics, because the exporter takes a Resource, we could customize this at creation time. It's a rabbit hole that we should discuss. 
* With the metrics exporter customizer functionality now, users can override and customize every aspect (including resource), but it's honestly pretty challenging to get correct, especially if you want disk buffering …

Configure metrics export

---

buildSrc/src/main/kotlin/otel.android-library-conventions.gradle.kts
instrumentation/httpurlconnection/library/src/main/java/io/opentelemetry/instrumentation/library/httpurlconnection/HttpUrlReplacements.java

As discussed in today's sig meeting about issue #682, I removed the added by default core library desugaring from android lib conventions. 
Project assembles fine but `./gradlew check `errors out on `lintDebug` task with 56 instances of requiring API level 24/26 or desugaring, as our minSdk = 21 :
We [earlier](https://github.com/open-telemetry/opentelemetry-android/blob/0e1d3fd9e4a3b83855facfecfba7c62532895250/instrumentation/httpurlconnection/library/src/main/java/io/opentelemetry/instrumentation/library/httpurlconnection/HttpUrlReplacements.java#L109) used a `@SuppressLint('NewApi')` annotation to suppress such warning instead of creating a lint baseline file (as maintaining that is tedious) : 
@RequiresApi might not be correct here as it does not necessarily need that API level but can …

Remove core library desugaring from android lib conventions

---

.github/workflows/add-stale-label.yaml

The current schedule unnecessarily clogs up the actions history, and we really don't need it to be that frequent.

Relax issue mgmt from every hour to every 8 hours.

---

.github/renovate.json5
settings.gradle.kts

PR builds are taking in excess of 15 minutes, which seems excessive. In order to help troubleshoot, we are enabling build scans.

Add gradle build scans

---

core/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
core/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java

Resolves #765.
A few notes about this changeset:
* I also removed the excessive `checkNotBuilt()` functionality from all the setters. I think this is nonstandard and not really necessary -- I expect that most developers will understand that the builder is to be used just once and that calling setters or changing the builder state after calling build doesn't have expected results. I don't see the need to throw the exception.
* There is a subtle and somewhat complex ordering challenge with customizers that add processors for spans and logs. In the `applyConfig()` method is where we add in various customers that add processors, but we call `applyConfig()` from within `build()`...which means that we are adding those LATE in the lifecycle, and after the user's other customizers and thus after …

Respect screen attrs config for logs

---

buildSrc/src/main/kotlin/otel.publish-conventions.gradle.kts

Resolves #533 if we like it.
We haven't really discussed this, but after reviewing #533 it seems that the main issue is that there is inconsistency with the two modules (okhttp, httpurlconnection) that are nested and have library+agent components. This prepends `instrumentation` in those cases where it is missing. The result, for example, looks like this:
```xml
<groupId>io.opentelemetry.android</groupId>
<artifactId>instrumentation-okhttp-3.0-agent</artifactId>
```
and similarly 
```xml
<groupId>io.opentelemetry.android</groupId>
<artifactId>instrumentation-httpurlconnection-agent</artifactId>
```
(and the two `-library` versions also not shown here).

[breaking] Adjust artifact coordinates for nested instrumentations

---

CHANGELOG.md
instrumentation/crash/README.md
instrumentation/crash/src/main/java/io/opentelemetry/android/instrumentation/crash/CrashReporter.java
instrumentation/crash/src/test/java/io/opentelemetry/android/instrumentation/crash/CrashReporterTest.java

See here: https://github.com/open-telemetry/semantic-conventions/blob/727700406f9e6cc3f4e4680a81c4c28f2eb71569/docs/attributes-registry/exception.md#deprecated-exception-attributes
Very little value in a hard-coded attribute value anyway. 😁

Remove deprecated EXCEPTION_ESCAPED

---

.github/renovate.json5

Looks like we are at least 5 version behind on semconv due to a problem with renovate. We think this will help clear that up, and we will expect a renovate update shortly after this is merged.
We need to include io.opentelemetry.proto and .semconv packages in the `ignoreUnstable: false` section.

Update renovate rules 

---

.github/renovate.json5

to pin digests and to group github actions PR updates to once a week since you'll get more now that they're pinned

Update Renovate config

---

core/src/main/java/io/opentelemetry/android/features/diskbuffering/DiskBufferingConfig.kt

As per [discussion](https://github.com/open-telemetry/opentelemetry-android/pull/773) on caching approach, it is preferable to have less cache size allocation by default.

Decrease default max cache size 60mb -> 10mb

---

instrumentation/startup/src/main/java/io/opentelemetry/android/instrumentation/startup/SdkInitializationEvents.kt
instrumentation/startup/src/test/java/io/opentelemetry/android/instrumentation/startup/SdkInitializationEventsTest.kt

Store init events in a thread safe queue and keep a reference to the created `EventLogger` when `finish()` is called after all the instrumentation has initialized. 
When an event is added - if it's `EventLogger` reference is not null, emit all the stored event, as it means an event has arrived after finished as been called.
If init events never appear after `finish()` is called, this will simply be a no-op. If they do, this will ensure they are properly emitted.

Emit log for every instrumentation init event

---

gradle/libs.versions.toml
instrumentation/slowrendering/src/main/java/io/opentelemetry/android/instrumentation/slowrendering/SlowRenderingInstrumentation.java

Supersedes https://github.com/open-telemetry/opentelemetry-android/pull/824
The warning was triggered because [the SDK lint check is now smarter](https://issuetracker.google.com/issues/373506498#comment6), so it sees that we had annotated a method with `@RequiresApi(N)` and thought that a second validation inside the method wasn't needed. However, the annotation was there for info purposes, as this is an SPI method that should always be called regardless of the environment, therefore it seems like this is a false-positive from the check, so I removed the `@RequiresApi` annotation to avoid it.

Addressing lint warning

---

build.gradle.kts

Kotlin 1.7 is now deprecated. Kotlin 1.8 came out more than 2 years ago, so this should be a reasonable upgrade.

Require kotlin 1.8+

---

core/src/main/java/io/opentelemetry/android/features/diskbuffering/DiskBufferingConfig.kt
core/src/main/java/io/opentelemetry/android/internal/features/persistence/DiskManager.kt
core/src/test/java/io/opentelemetry/android/internal/features/persistence/DiskManagerTest.kt

Fixes #859 by giving the flexibility to the SDK's users to choose a `signalsBufferDir` other than one used by default.

Add `DiskBufferingConfig.signalsBufferDir`

---

opentelemetry-android-bom/build.gradle.kts

The lack of description was causing the pom validation to [fail during the release](https://github.com/open-telemetry/opentelemetry-android/actions/runs/13724646433/job/38388065005). This should fix that.

Add bom description

---

core/build.gradle.kts
instrumentation/volley/library/build.gradle.kts

The presence of these lines is causing a build warning:
Seems like removing them with AGP 8.9.0 should be safe.

Remove old/outdated explicit build tools version

---

README.md
instrumentation/activity/README.md
instrumentation/fragment/README.md

Part of #742: created the fragment instrumentation readme and corrected activity instrumentation readme (added missed spans, span events and an attribute, corrected the `activity.name` attribute name to `activityName`, which is a worse, but reflecting reality name  (#865)).

Fragment readme creation and activity readme correction.

---

instrumentation/crash/README.md
instrumentation/crash/build.gradle.kts
instrumentation/crash/src/main/java/io/opentelemetry/android/instrumentation/crash/CrashReporter.java
instrumentation/crash/src/test/java/io/opentelemetry/android/instrumentation/crash/CrashReporterTest.java

During SIG review today, we noticed that the log record for crash still had the event name attribute set. This changes it to use the top-level event field on the LogRecord.

Use event name for crash event (instead of attr)

---

android-agent/src/main/kotlin/io/opentelemetry/android/agent/OtelRumConfigExtensions.kt
core/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
core/src/main/java/io/opentelemetry/android/internal/features/networkattrs/NetworkAttributesLogRecordAppender.kt
instrumentation/network/README.md
instrumentation/network/build.gradle.kts
instrumentation/network/src/main/java/io/opentelemetry/android/instrumentation/network/NetworkApplicationListener.java
instrumentation/network/src/main/java/io/opentelemetry/android/instrumentation/network/NetworkChangeAttributesExtractor.java
instrumentation/network/src/main/java/io/opentelemetry/android/instrumentation/network/NetworkChangeInstrumentation.java
instrumentation/network/src/main/java/io/opentelemetry/android/instrumentation/network/NetworkChangeMonitor.java
instrumentation/network/src/test/java/io/opentelemetry/android/instrumentation/network/NetworkChangeMonitorTest.java

The network change event is currently a zero-duration span. We want to migrate these to actual OpenTelemetry log-based events. This does that work, and also introduces a (global) `LogRecordProcessor` named `NetworkAttributesLogRecordAppender` that (when configured) always appends the global log attributes to all logs/events (similar to the NetworkAttributesSpanAppender).

Migrate network change event from zero-duration span to event

---

CHANGELOG.md
core/src/main/java/io/opentelemetry/android/OpenTelemetryRum.java
core/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
core/src/main/java/io/opentelemetry/android/SdkPreconfiguredRumBuilder.kt
core/src/main/java/io/opentelemetry/android/config/OtelRumConfig.java
core/src/main/java/io/opentelemetry/android/internal/session/SessionIdTimeoutHandler.kt
core/src/main/java/io/opentelemetry/android/internal/session/SessionManagerImpl.kt
core/src/test/java/io/opentelemetry/android/internal/session/SessionIdTimeoutHandlerTest.kt
core/src/test/java/io/opentelemetry/android/internal/session/SessionManagerImplTest.kt
session/src/main/kotlin/io/opentelemetry/android/session/SessionConfig.kt

Relates to #860.  See the thread over there for additional details.
Basically, we have always intended to have two session "timeouts" -- one that is a maximum absolute lifespan (4 hour default) and a background inactivity timeout (15 minute default). Somewhere along the way, these two values were blended, and the same timeout value was ultimately used for both.
The purpose of this PR is to once again separate these two times, and to make their names and usages more explicit.

Factor out and make session timeouts more explicit.

---

CHANGELOG.md
instrumentation/activity/README.md
instrumentation/activity/src/main/java/io/opentelemetry/android/instrumentation/activity/ActivityTracer.java
instrumentation/fragment/README.md
instrumentation/fragment/src/main/java/io/opentelemetry/android/instrumentation/fragment/FragmentTracer.java

Change attribute names in ActivityTracer.java and FragmentTracer.java
Issue: https://github.com/open-telemetry/opentelemetry-android/issues/865

Change attribute names in ActivityTracer.java and FragmentTracer.java

---

README.md
instrumentation/slowrendering/README.md

Changed `activityName` to `activity.name` in the slowrendering instrumentation readme (this one was dot separated from the start) and linked it in the main readme.

README minor fixes

---

instrumentation/activity/README.md
instrumentation/fragment/README.md

Fixes #919 (I believe kubecon is over so I just did it)
Removed angle brackets in fragment and activity instrumentation READMEs for markdown to render correctly.

Removed angled brackets for morkdown to render correctly

---

demo-app/src/main/java/io/opentelemetry/android/demo/shop/ui/products/ProductDetails.kt

Fixes #940 - took a line that adds an item to cart out of `else` for item being National Park Foundation Explorascope.

 Adding item to cart fix

---

instrumentation/volley/library/build.gradle.kts

This dependency is not required for the Volley module so I'm removing it.

Remove fragments dependency from Volley module

---

.github/renovate.json5

Saw this in a couple of java repos and thought we might benefit from this occasionally. It groups patch release PRs to once daily.

Group patch PRs to lower thrash

---

core/src/main/java/io/opentelemetry/android/NoopOpenTelemetryRum.java
core/src/main/java/io/opentelemetry/android/OpenTelemetryRum.java
core/src/main/java/io/opentelemetry/android/OpenTelemetryRumImpl.java
core/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java

add convenience event emitting api to OpenTelemetryRum

---

.github/workflows/release.yml

When doing the last release, I noticed that the release notes didn't contain the instrumentation version. I think this broke when we switched to using the alpha bom, so let's just use the version of the instrumentation api. Tested locally.

Use instrumentation api to get version

---

README.md
instrumentation/activity/README.md
instrumentation/android-log/README.md
instrumentation/anr/README.md
instrumentation/crash/README.md
instrumentation/fragment/README.md
instrumentation/network/README.md
instrumentation/okhttp3/README.md
instrumentation/slowrendering/README.md
instrumentation/view-click/README.md
instrumentation/volley/README.md

This changes the "experimental" word over to "development", to better align with the spec/semconv repos.
It adds a `README.md` for the new view-click instrumentation as well.

Documentation update

---

demo-app/src/main/java/io/opentelemetry/android/demo/OtelDemoApplication.kt

Re-enable disk buffering in the demo application by the the config object that was already created.

Enable disk buffering by default in the demo app

---

.github/repository-settings.md
build.gradle.kts

See this announcement: https://central.sonatype.org/news/20250326_ossrh_sunset/
and see this for the docs on this change https://github.com/gradle-nexus/publish-plugin?tab=readme-ov-file#publishing-to-maven-central-via-sonatype-central
A new user token has been generated and put into the GitHub secrets for this repo.

Update repos for sonatype central

---

instrumentation/view-click/build.gradle.kts
instrumentation/view-click/src/main/kotlin/io/opentelemetry/android/instrumentation/view/click/ViewClickEventGenerator.kt
instrumentation/view-click/src/main/kotlin/io/opentelemetry/android/instrumentation/view/click/internal/ViewUtils.kt
instrumentation/view-click/src/test/kotlin/io/opentelemetry/android/instrumentation/view/click/ViewClickInstrumentationTest.kt

We don't want to duplicate these constants now that they are available in the incubating semconv.

Use semantic conventions in click instrumentation

---

android-agent/src/main/kotlin/io/opentelemetry/android/agent/OpenTelemetryRumInitializer.kt

Small internal refactoring to use `SessionProvider` (smaller, broader interface) instead of `SessionManager`.

Return the less specific interface

---

android-agent/build.gradle.kts
instrumentation/okhttp3-websocket/library/build.gradle.kts
instrumentation/sessions/build.gradle.kts

Sonatype failed the 0.12.0 release, due to validation of 3 modules:
If this works, I'll cherry pick this back into main for the next release.

These modules fail to publish, due to missing platform dependency.

---

core/build.gradle.kts
core/src/main/java/io/opentelemetry/android/export/FilteringSpanExporter.java
core/src/main/java/io/opentelemetry/android/export/FilteringSpanExporterBuilder.java
gradle/libs.versions.toml

Resolves https://github.com/open-telemetry/opentelemetry-android/issues/76
- Integrates processors from the Java Contrib module
- Refactors FilteringSpanExporterBuilder to utilize InterceptableSpanExporter provided by the contrib library

Alter FilteringSpanExporter to leverage common code from contrib

---

opentelemetry-android-bom/build.gradle.kts

So the versions of these two are determined by gradle transitively from the top `opentelemetry-instrumentation-bom-alpha`. Their inclusion here causes the sonatype release process to fail validation (because they don't have explicit versions)....so let's just remove them. They shouldn't be necessary anyway.
And much like last time, I'll cherry pick this into main after the release.

Fix v0.13.0 release

---

.github/workflows/pr-check.yaml

Reduce the scope of verification of the demo-app by only assembling the release version and bypass debug, lint, and other checks. Doing debug will be even faster but having it go through release and the APK optimizations (including desugaring) is a more comprehensive verification.

Only run the assembleRelease target to verify the demo app compiles

---

services/src/test/java/io/opentelemetry/android/internal/services/network/CurrentNetworkProviderTest.kt

This test was running a lot of redundant API versions, which all has a fixed cost to spin up for the first time it was also unnecessarily reinitializing a lot of mocks that aren't inspected.
This PR curates a set of API versions that are relevant (i.e. code contains checks that differentiate behavior), as well as clean up some of the redundancies that are impactful.

Improve perf of current network tests

---

.github/workflows/release.yml
gradle.properties

This PR attempts to improve the build speed and overall build performance of the project by adopting Gradle's [suggested practices](https://docs.gradle.org/current/userguide/performance.html). This is loosely based on the performance tweaks we've adopted at Embrace over the last couple of years. Changes include:
1. Increasing the maximum heap size of the build
2. Various tweaks to JVM options for Gradle and the Gradle daemon that allow it to obtain more memory, if required
3. Enables parallel execution, which allows unrelated Gradle tasks to run in parallel rather than sequentially
4. Enables build caching
5. Enables configuration caching, which can drastically reduce the time required for the configuration phase of the build
6. Enables parallel storing of the configuration cache
Not all …

Improve build speed by altering gradle.properties

---

buildSrc/src/main/kotlin/otel.android-library-conventions.gradle.kts

Configuring [`maxParallelForks` for JVM tests](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxParallelForks) allows test classes to run in parallel. This can improve test execution times particularly if test cases are distributed across lots of different source files. Generally speaking this shouldn't cause problems unless tests are accessing shared objects/resources, which doesn't seem to be the case in this project.

Specify maxParallelForks for JVM tests

---

core/src/main/java/io/opentelemetry/android/NoopOpenTelemetryRum.java
core/src/main/java/io/opentelemetry/android/OpenTelemetryRum.java
core/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
core/src/main/java/io/opentelemetry/android/OpenTelemetryRumImpl.kt
core/src/main/java/io/opentelemetry/android/SdkPreconfiguredRumBuilder.kt
core/src/main/java/io/opentelemetry/android/features/diskbuffering/scheduler/DefaultExportScheduleHandler.kt
core/src/main/java/io/opentelemetry/android/features/diskbuffering/scheduler/DefaultExportScheduler.kt
instrumentation/android-instrumentation/src/main/java/io/opentelemetry/android/instrumentation/AndroidInstrumentation.kt
instrumentation/slowrendering/src/main/java/io/opentelemetry/android/instrumentation/slowrendering/SlowRenderListener.java
instrumentation/slowrendering/src/main/java/io/opentelemetry/android/instrumentation/slowrendering/SlowRenderingInstrumentation.java
instrumentation/slowrendering/src/test/java/io/opentelemetry/android/instrumentation/slowrendering/SlowRenderListenerTest.java

Related to #1071.
So this just starts the process of being able to uninstall instrumentation and shut down the sdk. It should not be considered a complete solution, because I only picked up a single instrumentation to see how it would feel to shut down. 
If we like this approach, I can create a tracking issue for the other instrumentations and we can knock those uninstalls out one-at-a-time.

OpenTelemetryRum.shutdown() and instrumentation uninstall

---

android-agent/src/main/kotlin/io/opentelemetry/android/agent/OpenTelemetryRumInitializer.kt
instrumentation/anr/build.gradle.kts
instrumentation/anr/src/main/java/io/opentelemetry/android/instrumentation/anr/AnrDetector.java
instrumentation/anr/src/main/java/io/opentelemetry/android/instrumentation/anr/AnrInstrumentation.java
instrumentation/anr/src/main/java/io/opentelemetry/android/instrumentation/anr/AnrWatcher.kt
instrumentation/anr/src/test/java/io/opentelemetry/android/instrumentation/anr/AnrDetectorTest.java
instrumentation/common-api/src/main/java/io/opentelemetry/android/instrumentation/common/EventAttributesExtractor.kt
instrumentation/crash/build.gradle.kts
instrumentation/crash/src/main/java/io/opentelemetry/android/instrumentation/crash/CrashReporter.java
instrumentation/crash/src/main/java/io/opentelemetry/android/instrumentation/crash/CrashReporterInstrumentation.java
instrumentation/crash/src/main/java/io/opentelemetry/android/instrumentation/crash/RuntimeDetailsExtractor.java
instrumentation/crash/src/test/java/io/opentelemetry/android/instrumentation/crash/CrashReporterTest.java
instrumentation/crash/src/test/java/io/opentelemetry/android/instrumentation/crash/RuntimeDetailsExtractorTest.java

So the design of the `AttributesExtractor` class is tightly tied in with how the instrumentation api is designed, which is focused squarely on tracing and making spans. As a result, the `AttributesExtractor` has `onStart()` and `onEnd()` methods which don't really line up with point-in-time eventing. This leads to clumsy implementations that have a `Void` generic type and an empty/useless `onEnd()`. The `onStart()` api itself is also kinda gross, because it expects/requires implementations to just cause side effects on the `AttributesBuilder` that is passed to it (presumably for optimization/performance reasons?).
This introduces a new interface called `EventAttributesExtractor` that takes the parent context and a "subject" and produces `Attributes`. Callers/users of the …

Add event attribute extractor

---

android-agent/api/android-agent.api
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/otel.android-library-conventions.gradle.kts
common/api/common.api
core/api/core.api
gradle/libs.versions.toml
instrumentation/activity/api/activity.api
instrumentation/android-instrumentation/api/android-instrumentation.api
instrumentation/android-log/agent/api/agent.api
instrumentation/android-log/library/api/library.api
instrumentation/anr/api/anr.api
instrumentation/common-api/api/common-api.api
instrumentation/compose/click/api/click.api
instrumentation/crash/api/crash.api
instrumentation/fragment/api/fragment.api
instrumentation/httpurlconnection/agent/api/agent.api
instrumentation/httpurlconnection/library/api/library.api
instrumentation/network/api/network.api
instrumentation/okhttp3-websocket/agent/api/agent.api
instrumentation/okhttp3-websocket/library/api/library.api
instrumentation/okhttp3/agent/api/agent.api
instrumentation/okhttp3/library/api/library.api
instrumentation/sessions/api/sessions.api
instrumentation/slowrendering/api/slowrendering.api
instrumentation/startup/api/startup.api
instrumentation/view-click/api/view-click.api
instrumentation/volley/library/api/library.api
services/api/services.api
session/api/session.api

This changeset adds Kotlin's [binary compatibility validator](https://github.com/Kotlin/binary-compatibility-validator) which generates a dump of API signatures and checks whether the project source code matches the known dump, thus allowing any API changes to be detected. The project works on Java & Kotlin files that are publicly exposed. `./gradlew apiCheck` runs the task, `./gradlew apiDump` regenerates the API dump file. The check will automatically run with `./gradlew check` so CI should catch any regressions/changes in the public API.
I've added this to any module that applies the `otel.android-library-conventions` gradle script and have generated a dump file for the existing APIs.
Closes #217

Setup binary compatibility validator

---

CHANGELOG.md
instrumentation/volley/README.md
instrumentation/volley/library/src/main/java/io/opentelemetry/android/instrumentation/volley/VolleyTracing.java

As discussed today in the SIG, the Volley project has not had a release in ~4 years and we have chosen to deprecate it so that we may remove it in a future release.
This adds a changelog entry and logs a warning if someone uses it.

Deprecate volley instrumentation

---

instrumentation/httpurlconnection/README.md
instrumentation/okhttp3/README.md

Some java classes converted to kotlin and broke the links in the readme. Follows #1133 and #1139.

Fix links in markdown

---

.github/workflows/build.yaml
.github/workflows/release.yml

Our CI builds for `main` are currently failing the (snapshot) publish step ([example 1](https://github.com/open-telemetry/opentelemetry-android/actions/runs/17046150939/job/48322387165), [example 2](https://github.com/open-telemetry/opentelemetry-android/actions/runs/17046169176/job/48322451764)). 
This seems to be caused by a bug in gradle ([see this thread](https://youtrack.jetbrains.com/projects/KT/issues/KT-79047/Gradle-compileKotlin-fails-with-configuration-cache)). It should be fixed in the next version which is imminent, but until then let's get our build fixed.
I've also disabled it for our release process builds, because we anticipate releasing this week can can't necessarily wait for the fix.

Attempt to fix the build by disabling incremental kotlin compile 

---

CONTRIBUTING.md

In #1124 api compatibility checking was introduced -- pretty cool!
This just adds a note to the `CONTRIBUTING.md` file so that folks who may not have seen it before might better understand its purpose and how to use it.

Update CONTRIBUTING.md with api compat checking info

---

instrumentation/anr/src/main/java/io/opentelemetry/android/instrumentation/anr/AnrWatcher.kt
instrumentation/common-api/src/test/java/io/opentelemetry/android/instrumentation/common/ScreenNameExtractorTest.kt
services/src/test/java/io/opentelemetry/android/internal/services/periodicwork/PeriodicWorkTest.kt

Fixes some additional build warnings I spotted when running `./gradlew check`, mostly related to deprecated symbols that need to be invoked from test code.

Fix build warnings

---

.github/workflows/pr-check.yaml

Attempts to fix #1214 by setting up a Github action to upload coverage reports to codecov. I largely followed the [quick start instructions](https://docs.codecov.com/docs/quick-start) and used [this project in codecov](https://app.codecov.io/github/open-telemetry/opentelemetry-android/new).

Setup codecov github action

---

instrumentation/httpurlconnection/README.md
instrumentation/okhttp3-websocket/README.md
instrumentation/okhttp3/README.md

This PR updates and restructures multiple `README.md` files to solve Issue #742 
1. **New Telemetry Sections**  
- **HttpUrlConnection**  
- Added a dedicated Telemetry section describing the instrumentation scope for `io.opentelemetry.android.http-url-connection`.  
- Documented HTTP client span lifecycle (start/end), included relevant attributes (`http.method`, `http.url`, `http.status_code`, `http.flavor`, `net.peer.*`).  
- Explained propagation behavior and provided an example harvester configuration.  
- **OkHttp**  
- Added a Telemetry section detailing spans emitted by the OkHttp client.  
- Described attributes provided by `OkHttpAttributesGetter`.  
- Explained span naming conventions via `HttpSpanNameExtractor`.  
- **OkHttp WebSocket**  
- Added a Telemetry section describing …

docs(instrumentation): add telemetry descriptions for httpurlconnection, okhttp3 and okhttp3-websocket (Issue #742)

---

README.md
docs/EXPORTER_CHAIN.md

This pull request introduces documentation for the new Exporter Chain feature in the OpenTelemetry Android RUM SDK. The main goal is to explain how the SDK handles asynchronous exporter initialization, buffering, and customization, ensuring reliable telemetry export even during startup or offline scenarios.
**Documentation Additions:**
* Added a new `EXPORTER_CHAIN.md` document detailing the exporter delegation chain, including in-memory and disk buffering, asynchronous initialization, and customization hooks.
* Updated `README.md` to reference the new Exporter Chain feature and documentation, highlighting its purpose and usage.
Fills a gap in documentation around exporter-chain internals, configuration, and extension hooks that was request in [Issue …

docs(exporter-chain): add exporter chain overview with default

---

android-agent/api/android-agent.api
android-agent/src/main/kotlin/io/opentelemetry/android/Incubating.kt
android-agent/src/main/kotlin/io/opentelemetry/android/agent/OpenTelemetryRumInitializer.kt
android-agent/src/main/kotlin/io/opentelemetry/android/agent/session/SessionConfig.kt

Adds the `Incubating` annotation which [enforces `RequiresOptIn`](https://kotlinlang.org/api/core/kotlin-stdlib/kotlin/-requires-opt-in/) on any symbol with the annotation. This results in a compiler warning for any consumer of symbols from the library that they must suppress to get rid of the warnings.
I've only added this to `SessionConfig` to demonstrate how the annotation works. `OpenTelemetryRumInitializer` has opted in to the incubating API as it uses the `SessionConfig` symbol.
I haven't added the annotation to anywhere else on the API surface - that's probably something that should be discussed as part of the 1.0.0 roadmap talks. Personally I feel like adding this annotation to any part of the public API surface folks aren't confident will remain the same would be good if it meant …

Add Incubating annotation to indicate unstable APIs

---

build.gradle.kts
buildSrc/src/main/kotlin/otel.publish-conventions.gradle.kts

This is to enable a similar mechanism to the one used in OTel Java Contrib, for example, where a module that has the property `otel.stable=true` doesn't get the `-alpha` suffix on its version. This will allow us to mark the `android-agent` as stable in the future.

Adding support for otel.stable property
