- .github/workflows/pr-check.yaml
- buildSrc/src/main/kotlin/otel.errorprone-conventions.gradle.kts
> Add PR check

- renovate.json
- renovate.json5
Also renamed the renovate file to allow for json comments.
Relates to #22
> Limit a couple of renovate packages until gradle plugin is ready

- .github/workflows/build.yaml
Included the reusable workflow but with the wrong `needs`.
> Fix build breakage

- CONTRIBUTING.md
- README.md
- code-of-conduct.md
* Add approver/maintainer section to contributing in README
* Fix up grammar in CONTRIBUTING
* Add features list
* Add missing code of conduct
> Update README and misc docs updates

- .github/repository-settings.md
I added these two to the repo secrets for publishing.
> Update repo settings with sonatype secrets

- instrumentation/src/main/java/io/opentelemetry/android/SessionIdRatioBasedSampler.java
- instrumentation/src/main/java/io/opentelemetry/android/instrumentation/ScreenNameExtractor.java
- instrumentation/src/main/java/io/opentelemetry/android/instrumentation/activity/ActivityTracer.java
- instrumentation/src/main/java/io/opentelemetry/android/instrumentation/fragment/FragmentTracer.java
- instrumentation/src/main/java/io/opentelemetry/android/instrumentation/lifecycle/AndroidLifecycleInstrumentationBuilder.java
- instrumentation/src/main/java/io/opentelemetry/android/instrumentation/startup/AppStartupTimer.java
I tried #46 locally and it already pointed out a few issues, so I tried to get ahead of that and clean those up here.
> Corrections for nullaway and errorprone

- .github/repository-settings.md
Adding 2 GPG secrets to the repo settings
> Add gpg settings

- README.md
- buildSrc/src/main/kotlin/otel.java-library-conventions.gradle.kts
> Corelib desugaring requirement

- auto-instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/OkHttp3Singletons.java
- gradle/libs.versions.toml
Supersedes https://github.com/open-telemetry/opentelemetry-android/pull/152
> Addressing java-instrumentation class renamed

- .github/workflows/release.yml
> Automatically create and push tag when doing release builds

- build.gradle.kts
> Removing maven snapshot repo

- .github/workflows/add-stale-label.yaml
- .github/workflows/remove-needs-author-feedback.yaml
Resolves #243.
These are copied over from upstream instrumentation repo as linked in #243. Because this repo isn't yet as active, I decided to leave stale around for 2 weeks before closing.
> Add issue automation

- CHANGELOG.md
- README.md
- gradle.properties
> Update changelog and version after 0.4.0 release

- instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
- instrumentation/src/main/java/io/opentelemetry/android/internal/processors/GlobalAttributesLogRecordAppender.kt
- instrumentation/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java
- instrumentation/src/test/java/io/opentelemetry/android/internal/processors/GlobalAttributesLogRecordAppenderTest.kt
> Global attrs for logs

- .github/workflows/reusable-markdown-link-check.yml
Similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10797
> Pin markdown-link-check version to fix broken build

- .github/renovate.json5
- gradle/libs.versions.toml
Not sure why these didn't get renovate attention, but they should be updated.
> Update upstream deps

- android-agent/build.gradle.kts
- android-agent/src/main/java/io/opentelemetry/android/AndroidResource.java
- android-agent/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
- android-agent/src/main/java/io/opentelemetry/android/features/diskbuffering/DiskBufferingConfiguration.java
- android-agent/src/main/java/io/opentelemetry/android/features/diskbuffering/SignalFromDiskExporter.kt
- buildSrc/src/main/kotlin/otel.errorprone-conventions.gradle.kts
- gradle/libs.versions.toml
- instrumentation/activity/src/main/java/io/opentelemetry/android/instrumentation/activity/ActivityTracer.java
- instrumentation/anr/src/main/java/io/opentelemetry/android/instrumentation/anr/StackTraceFormatter.java
- instrumentation/crash/build.gradle.kts
- instrumentation/crash/src/main/java/io/opentelemetry/android/instrumentation/crash/CrashReporter.java
- instrumentation/network/build.gradle.kts
- instrumentation/network/src/main/java/io/opentelemetry/android/instrumentation/network/CurrentNetworkAttributesExtractor.java
- instrumentation/network/src/main/java/io/opentelemetry/android/instrumentation/network/NetworkChangeAttributesExtractor.java
- instrumentation/network/src/main/java/io/opentelemetry/android/instrumentation/network/NetworkState.java
- instrumentation/network/src/main/java/io/opentelemetry/android/instrumentation/network/PostApi28NetworkDetector.java
- instrumentation/network/src/test/java/io/opentelemetry/android/instrumentation/network/PostApi28NetworkDetectorTest.java
- instrumentation/volley/library/build.gradle.kts
- instrumentation/volley/library/src/main/java/io/opentelemetry/android/instrumentation/volley/VolleyHttpClientAttributesGetter.java
- instrumentation/volley/library/src/main/java/io/opentelemetry/android/instrumentation/volley/VolleyResponseAttributesExtractor.java
Just a maintenance/cleanup task here.
> Addressing a set of semantic conventions deprecations and other warnings

- .github/workflows/codeql-daily.yml
Fixes build breakage like https://github.com/open-telemetry/opentelemetry-android/actions/runs/8995996244/job/24711814010#step:5:201
> Touch local.properties for codeql

- android-agent/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
- android-agent/src/main/java/io/opentelemetry/android/SessionIdTimeoutHandler.java
- android-agent/src/test/java/io/opentelemetry/android/SessionIdTimeoutHandlerTest.java
Just a small follow-up from #330.
> Use duration for session timeout handler

- gradle/libs.versions.toml
- instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/OkHttp3Singletons.java
> Bumping up java instrumentation version and adjusting to api changes

- .github/workflows/draft-change-log-entries.yaml
[Seems like](https://github.com/open-telemetry/opentelemetry-android/actions/runs/9348015347/job/25726243291) the script wasn't runnable.
> Making changelog script runnable

- README.md
They have been active contributors for a while now and their inputs in PRs, SIG, and Slack have helped define OTel Android's shape. Thank you for your contributions @bidetofevil @marandaneto !
> Adding Hanson and Manoel as approvers

- core/src/main/java/io/opentelemetry/android/OpenTelemetryRum.java
- core/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
- core/src/main/java/io/opentelemetry/android/SdkPreconfiguredRumBuilder.kt
- core/src/main/java/io/opentelemetry/android/internal/services/ServiceManager.kt
- core/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java
> Initializing services when creating a preconfigured rum instance

- demo-app/build.gradle.kts
- demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/AstronomyShopActivity.kt
- demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/Navigation.kt
- demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/cart/Cart.kt
- demo-app/src/main/java/io/opentelemetry/android/demo/ui/shop/cart/CheckoutInfo.kt
Demo-app: implemented a buyer's details screen after clicking checkout button in cart.
> Checkout info

- buildSrc/src/main/kotlin/otel.android-library-conventions.gradle.kts
- gradle/libs.versions.toml
- instrumentation/httpurlconnection/library/src/main/java/io/opentelemetry/instrumentation/library/httpurlconnection/HttpUrlReplacements.java
- instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/OkHttp3Singletons.java
- instrumentation/startup/src/test/java/io/opentelemetry/android/instrumentation/startup/SdkInitializationEventsTest.kt
- instrumentation/volley/library/src/test/java/io/opentelemetry/android/instrumentation/volley/TracingHurlStackTest.java
The main thing was to add the dependency on junit platform launcher, as described [here](https://discuss.gradle.org/t/running-tests-fails-set-up-problems/46616), in order to be compatible with Gradle 9. The other items just address other miscellaneous build warnings.
> Fix build warnings

- core/src/main/java/io/opentelemetry/android/internal/services/network/data/NetworkState.java
- core/src/main/java/io/opentelemetry/android/internal/services/network/detector/SimpleNetworkDetector.java
- core/src/test/java/io/opentelemetry/android/internal/services/network/detector/SimpleNetworkDetectorTest.java
This fixes https://github.com/open-telemetry/opentelemetry-android/issues/672
> Handle wired network transport type

- core/src/main/java/io/opentelemetry/android/internal/services/network/data/NetworkState.java
- gradle/libs.versions.toml
> Bumping otel instrumentation version

- core/consumer-rules.pro
- demo-app/build.gradle.kts
- demo-app/proguard-rules.pro
- demo-app/src/main/java/io/opentelemetry/android/demo/OtelDemoApplication.kt
- demo-app/src/main/java/io/opentelemetry/android/demo/shop/model/Product.kt
> R8 consumer rules

- CHANGELOG.md
Gets the changelog ready for the v0.9.0 release.
> Update changelog / prepare v0.9.0

- CHANGELOG.md
I screwed up the order and didn't merge the changelog PR before running the workflow that creates the release branch, so now I need to merge this in. Whoops!
* update changelog
* spotless
* Update CHANGELOG.md
> Update changelog / prepare v0.9.0 (#740)

- README.md
- instrumentation/activity/README.md
> Add docs for Activity instrumentation telemetry

- common/build.gradle.kts
- services/build.gradle.kts
- session/build.gradle.kts
> Adding publish conventions

- .github/renovate.json5
> Add rule to skip updates for gummy bears package

- session/build.gradle.kts
A quick PR to remove an unused dependency! :)
> Remove services module from session module dependencies

- android-agent/build.gradle.kts
- instrumentation/anr/README.md
> Add ANR docs

- .github/workflows/codeql-daily.yml
Motivated by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/13143, new feature described here https://github.blog/changelog/2024-12-17-find-and-fix-actions-workflows-vulnerabilities-with-codeql-public-preview/
> Add actions to codeql checks

- README.md
- instrumentation/crash/README.md
> Crash readme

- README.md
- instrumentation/network/README.md
> Add docs for network change

- .github/workflows/ossf-scorecard.yml
> Add OSSF scorecard workflow

- .fossa.yml
- .github/workflows/fossa.yml
> Add FOSSA license scanning

- .github/renovate.json5
Since docker images are also being pinned (#814)
> Less frequent Renovate

- .github/renovate.json5
See #834 and #835 that should have been combined.
> Group renovate semconv updates

- opentelemetry-android-bom/build.gradle.kts
Added the description in the release/0.10.x branch, so this merges it to main as well.
> Cherry pick from 61812e6a181cb05fb65b9322a6256b073a55f7cf

- RELEASING.md
> Adding release cadence info

- core/src/main/java/io/opentelemetry/android/OpenTelemetryRum.java
- core/src/main/java/io/opentelemetry/android/OpenTelemetryRumBuilder.java
- core/src/main/java/io/opentelemetry/android/SdkPreconfiguredRumBuilder.kt
- core/src/main/java/io/opentelemetry/android/config/OtelRumConfig.java
- core/src/test/java/io/opentelemetry/android/OpenTelemetryRumBuilderTest.java
- instrumentation/activity/src/main/java/io/opentelemetry/android/instrumentation/activity/ActivityLifecycleInstrumentation.kt
- instrumentation/android-instrumentation/src/main/java/io/opentelemetry/android/instrumentation/AndroidInstrumentation.kt
- instrumentation/android-instrumentation/src/test/java/io/opentelemetry/android/instrumentation/TestAndroidInstrumentation.kt
- instrumentation/anr/src/main/java/io/opentelemetry/android/instrumentation/anr/AnrInstrumentation.java
- instrumentation/crash/src/main/java/io/opentelemetry/android/instrumentation/crash/CrashReporterInstrumentation.java
- instrumentation/fragment/src/main/java/io/opentelemetry/android/instrumentation/fragment/FragmentLifecycleInstrumentation.kt
- instrumentation/httpurlconnection/library/src/main/java/io/opentelemetry/instrumentation/library/httpurlconnection/HttpUrlInstrumentation.java
- instrumentation/network/src/main/java/io/opentelemetry/android/instrumentation/network/NetworkChangeInstrumentation.java
- instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/OkHttpInstrumentation.java
- instrumentation/okhttp/websocket/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/websocket/internal/OkHttpWebsocketInstrumentation.java
- instrumentation/sessions/src/main/kotlin/io/opentelemetry/android/instrumentation/sessions/SessionInstrumentation.kt
- instrumentation/slowrendering/src/main/java/io/opentelemetry/android/instrumentation/slowrendering/SlowRenderingInstrumentation.java
- instrumentation/startup/src/main/java/io/opentelemetry/android/instrumentation/startup/StartupInstrumentation.kt
This is one idea about suppressing instrumentations. It adds a name to every instrumentation and then allows suppression of those instrumentations by name. 
May not be exactly what was asked, but relates to #851.
Curious what folks think. Thanks.
> Allow users to configure suppression of some instrumentations.

- instrumentation/slowrendering/README.md
- instrumentation/slowrendering/src/main/java/io/opentelemetry/android/instrumentation/slowrendering/SlowRenderListener.java
> Add README.md for slow rendering instrumentation

- instrumentation/okhttp3/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/OkHttpInstrumentation.java
> Fix links in javadocs

- RELEASING.md
Some minor tweaks noted during the most recent 0.12.x release process.
> Small improvements to RELEASING.md

- opentelemetry-android-bom/build.gradle.kts
> Remove transitive version-less dependencies from bom.

- buildSrc/src/main/kotlin/otel.android-app-conventions.gradle.kts
- buildSrc/src/main/kotlin/otel.android-dependency-conventions.gradle.kts
- buildSrc/src/main/kotlin/otel.android-library-conventions.gradle.kts
- demo-app/build.gradle.kts
- demo-app/gradle/libs.versions.toml
> Okhttp jvm android resolution

- services/src/main/java/io/opentelemetry/android/internal/services/network/CarrierFinder.java
- services/src/main/java/io/opentelemetry/android/internal/services/network/detector/NetworkDetectorImpl.kt
Add warning logs in Network detection logic when permission or feature check fails.
> Add more warning logs in Network detection 

- services/src/test/java/io/opentelemetry/android/internal/services/network/detector/NetworkDetectorTest.kt
> Network detector test migration to mockk

- services/src/test/java/io/opentelemetry/android/internal/services/applifecycle/ApplicationStateWatcherTest.kt
> refactor(services): replace Mockito with MockK in ApplicationStateWatcherTest.kt

- instrumentation/android-log/README.md
...just happened to notice these small things in the README.
> Small README typo fixes
